version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - main
image: Visual Studio 2022
init:
- ps: ''
before_build:
- ps: dotnet restore IpQualityScore.Net\IpQualityScore.Net.sln
build:
  project: IpQualityScore.Net\IpQualityScore.Net.sln
  verbosity: minimal
artifacts:
- path: .\**\*.nupkg
  name: NuGet
deploy:
- provider: NuGet
  name: production
  api_key:
    secure: zvlSLxH7RIMEC1VlAuVALWyyPGprsoBeyNQ9I1T+58D061Yy8xrAPes3IQXoWnqd
  on:
    branch: master
    appveyor_repo_tag: true